# This is a basic workflow to help you get started with Actions

name: AWS Deploy FrontEnd

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      CI: false # consider warning as error

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell

      - name: Where the fuck i am
        run:  ls -la /home/runner/work/frontend/frontend/src
        
      - name: install dependencies
        run : npm install

      - name: Build app
        run : npm run build --if-present

      - name: Create SSH Key file
        run: touch SSH.pem

      - name: Change permission
        run: chmod 600 SSH.pem

      - name: Write key
        run: echo "${{secrets.SSH}}" > SSH.pem

      - name: Display key
        run: more SSH.pem

      - name: Copy app
        run : rsync -rave "sudo ssh StrictHostKeyChecking=no -i SSH.pem" ./frontend/build/ ubuntu@ec2-18-193-43-186.eu-central-1.compute.amazonaws.com:/var/www/html
        
    # - name: SSH to server and run a deploy app script
    #   run: sudo ssh -o StrictHostKeyChecking=no -T ubuntu@18.193.129.54 -i "SSH.pem" "/home/ubuntu/deploy_app.sh &" 
