# This is a basic workflow to help you get started with Actions

name: AWS Deploy FrontEnd

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"    
  deploy:
    env:
     CI: false # consider warning as error
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2 # NEEDED otherwise the files of the repo won't be here

      - name: Install dependencies
        run : npm install

      - name: Build app
        run : npm run build --if-present

      - name: Create SSH Key file
        run: touch SSH.pem

      - name: Change permission
        run: chmod 600 SSH.pem

      - name: Write SSH key
        run: echo "${{secrets.SSH}}" > SSH.pem

      - name: Copy app files to AWS
        run : rsync -rave "sudo ssh -o StrictHostKeyChecking=no -i SSH.pem" ./build/ ubuntu@ec2-18-193-43-186.eu-central-1.compute.amazonaws.com:/var/www/html
